// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ml.proto

// Shared contract for SafeCity's server-side AI tier (apps/ml), called by the Go
// API (apps/api) over gRPC. NOTE: the real-time blind-walk CV stays on-device in
// apps/mobile — this service only handles photo moderation, OCR/scene
// description, and accessibility-feature inference from photos.

package mlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImageSource carries an image either inline or by URL (Supabase Storage).
type ImageSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*ImageSource_Image
	//	*ImageSource_ImageUrl
	Source        isImageSource_Source `protobuf_oneof:"source"`
	ContentType   string               `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // e.g. image/jpeg (optional hint)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSource) Reset() {
	*x = ImageSource{}
	mi := &file_ml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSource) ProtoMessage() {}

func (x *ImageSource) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSource.ProtoReflect.Descriptor instead.
func (*ImageSource) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{0}
}

func (x *ImageSource) GetSource() isImageSource_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ImageSource) GetImage() []byte {
	if x != nil {
		if x, ok := x.Source.(*ImageSource_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ImageSource) GetImageUrl() string {
	if x != nil {
		if x, ok := x.Source.(*ImageSource_ImageUrl); ok {
			return x.ImageUrl
		}
	}
	return ""
}

func (x *ImageSource) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type isImageSource_Source interface {
	isImageSource_Source()
}

type ImageSource_Image struct {
	Image []byte `protobuf:"bytes,1,opt,name=image,proto3,oneof"` // raw image bytes
}

type ImageSource_ImageUrl struct {
	ImageUrl string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3,oneof"` // URL the service fetches
}

func (*ImageSource_Image) isImageSource_Source() {}

func (*ImageSource_ImageUrl) isImageSource_Source() {}

type ModeratePhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageSource           `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeratePhotoRequest) Reset() {
	*x = ModeratePhotoRequest{}
	mi := &file_ml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeratePhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeratePhotoRequest) ProtoMessage() {}

func (x *ModeratePhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeratePhotoRequest.ProtoReflect.Descriptor instead.
func (*ModeratePhotoRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{1}
}

func (x *ModeratePhotoRequest) GetImage() *ImageSource {
	if x != nil {
		return x.Image
	}
	return nil
}

type ModeratePhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`                     // safe to publish
	NsfwScore     float64                `protobuf:"fixed64,2,opt,name=nsfw_score,json=nsfwScore,proto3" json:"nsfw_score,omitempty"` // 0..1
	Labels        []string               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`                          // detected categories
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                          // human-readable rejection reason, if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeratePhotoResponse) Reset() {
	*x = ModeratePhotoResponse{}
	mi := &file_ml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeratePhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeratePhotoResponse) ProtoMessage() {}

func (x *ModeratePhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeratePhotoResponse.ProtoReflect.Descriptor instead.
func (*ModeratePhotoResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{2}
}

func (x *ModeratePhotoResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ModeratePhotoResponse) GetNsfwScore() float64 {
	if x != nil {
		return x.NsfwScore
	}
	return 0
}

func (x *ModeratePhotoResponse) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ModeratePhotoResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DescribeSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageSource           `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // BCP-47, e.g. "uk"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeSceneRequest) Reset() {
	*x = DescribeSceneRequest{}
	mi := &file_ml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeSceneRequest) ProtoMessage() {}

func (x *DescribeSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeSceneRequest.ProtoReflect.Descriptor instead.
func (*DescribeSceneRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeSceneRequest) GetImage() *ImageSource {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *DescribeSceneRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type DescribeSceneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	OcrText       string                 `protobuf:"bytes,2,opt,name=ocr_text,json=ocrText,proto3" json:"ocr_text,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0..1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeSceneResponse) Reset() {
	*x = DescribeSceneResponse{}
	mi := &file_ml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeSceneResponse) ProtoMessage() {}

func (x *DescribeSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeSceneResponse.ProtoReflect.Descriptor instead.
func (*DescribeSceneResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeSceneResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DescribeSceneResponse) GetOcrText() string {
	if x != nil {
		return x.OcrText
	}
	return ""
}

func (x *DescribeSceneResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type InferFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageSource           `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // point_category hint (venue/transit/...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferFeaturesRequest) Reset() {
	*x = InferFeaturesRequest{}
	mi := &file_ml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferFeaturesRequest) ProtoMessage() {}

func (x *InferFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferFeaturesRequest.ProtoReflect.Descriptor instead.
func (*InferFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{5}
}

func (x *InferFeaturesRequest) GetImage() *ImageSource {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *InferFeaturesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// FeaturePrediction maps a feature catalog key to a predicted value.
type FeaturePrediction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                 // accessibility_features.key
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`             // yes | no | unknown
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0..1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeaturePrediction) Reset() {
	*x = FeaturePrediction{}
	mi := &file_ml_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturePrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturePrediction) ProtoMessage() {}

func (x *FeaturePrediction) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturePrediction.ProtoReflect.Descriptor instead.
func (*FeaturePrediction) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{6}
}

func (x *FeaturePrediction) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FeaturePrediction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FeaturePrediction) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type InferFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []*FeaturePrediction   `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferFeaturesResponse) Reset() {
	*x = InferFeaturesResponse{}
	mi := &file_ml_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferFeaturesResponse) ProtoMessage() {}

func (x *InferFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferFeaturesResponse.ProtoReflect.Descriptor instead.
func (*InferFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{7}
}

func (x *InferFeaturesResponse) GetFeatures() []*FeaturePrediction {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_ml_proto protoreflect.FileDescriptor

const file_ml_proto_rawDesc = "" +
	"\n" +
	"\bml.proto\x12\x0esafecity.ml.v1\"q\n" +
	"\vImageSource\x12\x16\n" +
	"\x05image\x18\x01 \x01(\fH\x00R\x05image\x12\x1d\n" +
	"\timage_url\x18\x02 \x01(\tH\x00R\bimageUrl\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentTypeB\b\n" +
	"\x06source\"I\n" +
	"\x14ModeratePhotoRequest\x121\n" +
	"\x05image\x18\x01 \x01(\v2\x1b.safecity.ml.v1.ImageSourceR\x05image\"\x82\x01\n" +
	"\x15ModeratePhotoResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x1d\n" +
	"\n" +
	"nsfw_score\x18\x02 \x01(\x01R\tnsfwScore\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"e\n" +
	"\x14DescribeSceneRequest\x121\n" +
	"\x05image\x18\x01 \x01(\v2\x1b.safecity.ml.v1.ImageSourceR\x05image\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"t\n" +
	"\x15DescribeSceneResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x19\n" +
	"\bocr_text\x18\x02 \x01(\tR\aocrText\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\"e\n" +
	"\x14InferFeaturesRequest\x121\n" +
	"\x05image\x18\x01 \x01(\v2\x1b.safecity.ml.v1.ImageSourceR\x05image\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"[\n" +
	"\x11FeaturePrediction\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\"V\n" +
	"\x15InferFeaturesResponse\x12=\n" +
	"\bfeatures\x18\x01 \x03(\v2!.safecity.ml.v1.FeaturePredictionR\bfeatures2\xa5\x02\n" +
	"\tMLService\x12\\\n" +
	"\rModeratePhoto\x12$.safecity.ml.v1.ModeratePhotoRequest\x1a%.safecity.ml.v1.ModeratePhotoResponse\x12\\\n" +
	"\rDescribeScene\x12$.safecity.ml.v1.DescribeSceneRequest\x1a%.safecity.ml.v1.DescribeSceneResponse\x12\\\n" +
	"\rInferFeatures\x12$.safecity.ml.v1.InferFeaturesRequest\x1a%.safecity.ml.v1.InferFeaturesResponseB,Z*github.com/safecity/api/internal/mlpb;mlpbb\x06proto3"

var (
	file_ml_proto_rawDescOnce sync.Once
	file_ml_proto_rawDescData []byte
)

func file_ml_proto_rawDescGZIP() []byte {
	file_ml_proto_rawDescOnce.Do(func() {
		file_ml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_proto_rawDesc), len(file_ml_proto_rawDesc)))
	})
	return file_ml_proto_rawDescData
}

var file_ml_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ml_proto_goTypes = []any{
	(*ImageSource)(nil),           // 0: safecity.ml.v1.ImageSource
	(*ModeratePhotoRequest)(nil),  // 1: safecity.ml.v1.ModeratePhotoRequest
	(*ModeratePhotoResponse)(nil), // 2: safecity.ml.v1.ModeratePhotoResponse
	(*DescribeSceneRequest)(nil),  // 3: safecity.ml.v1.DescribeSceneRequest
	(*DescribeSceneResponse)(nil), // 4: safecity.ml.v1.DescribeSceneResponse
	(*InferFeaturesRequest)(nil),  // 5: safecity.ml.v1.InferFeaturesRequest
	(*FeaturePrediction)(nil),     // 6: safecity.ml.v1.FeaturePrediction
	(*InferFeaturesResponse)(nil), // 7: safecity.ml.v1.InferFeaturesResponse
}
var file_ml_proto_depIdxs = []int32{
	0, // 0: safecity.ml.v1.ModeratePhotoRequest.image:type_name -> safecity.ml.v1.ImageSource
	0, // 1: safecity.ml.v1.DescribeSceneRequest.image:type_name -> safecity.ml.v1.ImageSource
	0, // 2: safecity.ml.v1.InferFeaturesRequest.image:type_name -> safecity.ml.v1.ImageSource
	6, // 3: safecity.ml.v1.InferFeaturesResponse.features:type_name -> safecity.ml.v1.FeaturePrediction
	1, // 4: safecity.ml.v1.MLService.ModeratePhoto:input_type -> safecity.ml.v1.ModeratePhotoRequest
	3, // 5: safecity.ml.v1.MLService.DescribeScene:input_type -> safecity.ml.v1.DescribeSceneRequest
	5, // 6: safecity.ml.v1.MLService.InferFeatures:input_type -> safecity.ml.v1.InferFeaturesRequest
	2, // 7: safecity.ml.v1.MLService.ModeratePhoto:output_type -> safecity.ml.v1.ModeratePhotoResponse
	4, // 8: safecity.ml.v1.MLService.DescribeScene:output_type -> safecity.ml.v1.DescribeSceneResponse
	7, // 9: safecity.ml.v1.MLService.InferFeatures:output_type -> safecity.ml.v1.InferFeaturesResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ml_proto_init() }
func file_ml_proto_init() {
	if File_ml_proto != nil {
		return
	}
	file_ml_proto_msgTypes[0].OneofWrappers = []any{
		(*ImageSource_Image)(nil),
		(*ImageSource_ImageUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_proto_rawDesc), len(file_ml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_proto_goTypes,
		DependencyIndexes: file_ml_proto_depIdxs,
		MessageInfos:      file_ml_proto_msgTypes,
	}.Build()
	File_ml_proto = out.File
	file_ml_proto_goTypes = nil
	file_ml_proto_depIdxs = nil
}
