// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ml.proto

// Shared contract for SafeCity's server-side AI tier (apps/ml), called by the Go
// API (apps/api) over gRPC. NOTE: the real-time blind-walk CV stays on-device in
// apps/mobile — this service only handles photo moderation, OCR/scene
// description, and accessibility-feature inference from photos.

package mlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLService_ModeratePhoto_FullMethodName = "/safecity.ml.v1.MLService/ModeratePhoto"
	MLService_DescribeScene_FullMethodName = "/safecity.ml.v1.MLService/DescribeScene"
	MLService_InferFeatures_FullMethodName = "/safecity.ml.v1.MLService/InferFeatures"
)

// MLServiceClient is the client API for MLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLServiceClient interface {
	// ModeratePhoto decides whether an uploaded photo is safe to publish.
	ModeratePhoto(ctx context.Context, in *ModeratePhotoRequest, opts ...grpc.CallOption) (*ModeratePhotoResponse, error)
	// DescribeScene returns OCR text + a scene description (accessibility fallback).
	DescribeScene(ctx context.Context, in *DescribeSceneRequest, opts ...grpc.CallOption) (*DescribeSceneResponse, error)
	// InferFeatures predicts accessibility feature values from a point photo.
	InferFeatures(ctx context.Context, in *InferFeaturesRequest, opts ...grpc.CallOption) (*InferFeaturesResponse, error)
}

type mLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLServiceClient(cc grpc.ClientConnInterface) MLServiceClient {
	return &mLServiceClient{cc}
}

func (c *mLServiceClient) ModeratePhoto(ctx context.Context, in *ModeratePhotoRequest, opts ...grpc.CallOption) (*ModeratePhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModeratePhotoResponse)
	err := c.cc.Invoke(ctx, MLService_ModeratePhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) DescribeScene(ctx context.Context, in *DescribeSceneRequest, opts ...grpc.CallOption) (*DescribeSceneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeSceneResponse)
	err := c.cc.Invoke(ctx, MLService_DescribeScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) InferFeatures(ctx context.Context, in *InferFeaturesRequest, opts ...grpc.CallOption) (*InferFeaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferFeaturesResponse)
	err := c.cc.Invoke(ctx, MLService_InferFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLServiceServer is the server API for MLService service.
// All implementations must embed UnimplementedMLServiceServer
// for forward compatibility.
type MLServiceServer interface {
	// ModeratePhoto decides whether an uploaded photo is safe to publish.
	ModeratePhoto(context.Context, *ModeratePhotoRequest) (*ModeratePhotoResponse, error)
	// DescribeScene returns OCR text + a scene description (accessibility fallback).
	DescribeScene(context.Context, *DescribeSceneRequest) (*DescribeSceneResponse, error)
	// InferFeatures predicts accessibility feature values from a point photo.
	InferFeatures(context.Context, *InferFeaturesRequest) (*InferFeaturesResponse, error)
	mustEmbedUnimplementedMLServiceServer()
}

// UnimplementedMLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLServiceServer struct{}

func (UnimplementedMLServiceServer) ModeratePhoto(context.Context, *ModeratePhotoRequest) (*ModeratePhotoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModeratePhoto not implemented")
}
func (UnimplementedMLServiceServer) DescribeScene(context.Context, *DescribeSceneRequest) (*DescribeSceneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeScene not implemented")
}
func (UnimplementedMLServiceServer) InferFeatures(context.Context, *InferFeaturesRequest) (*InferFeaturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InferFeatures not implemented")
}
func (UnimplementedMLServiceServer) mustEmbedUnimplementedMLServiceServer() {}
func (UnimplementedMLServiceServer) testEmbeddedByValue()                   {}

// UnsafeMLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLServiceServer will
// result in compilation errors.
type UnsafeMLServiceServer interface {
	mustEmbedUnimplementedMLServiceServer()
}

func RegisterMLServiceServer(s grpc.ServiceRegistrar, srv MLServiceServer) {
	// If the following call panics, it indicates UnimplementedMLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLService_ServiceDesc, srv)
}

func _MLService_ModeratePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeratePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).ModeratePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_ModeratePhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).ModeratePhoto(ctx, req.(*ModeratePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_DescribeScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).DescribeScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_DescribeScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).DescribeScene(ctx, req.(*DescribeSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_InferFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).InferFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_InferFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).InferFeatures(ctx, req.(*InferFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLService_ServiceDesc is the grpc.ServiceDesc for MLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "safecity.ml.v1.MLService",
	HandlerType: (*MLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModeratePhoto",
			Handler:    _MLService_ModeratePhoto_Handler,
		},
		{
			MethodName: "DescribeScene",
			Handler:    _MLService_DescribeScene_Handler,
		},
		{
			MethodName: "InferFeatures",
			Handler:    _MLService_InferFeatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml.proto",
}
