# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x0esafecity.ml.v1\"S\n\x0bImageSource\x12\x0f\n\x05image\x18\x01 \x01(\x0cH\x00\x12\x13\n\timage_url\x18\x02 \x01(\tH\x00\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\tB\x08\n\x06source\"B\n\x14ModeratePhotoRequest\x12*\n\x05image\x18\x01 \x01(\x0b\x32\x1b.safecity.ml.v1.ImageSource\"]\n\x15ModeratePhotoResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x12\n\nnsfw_score\x18\x02 \x01(\x01\x12\x0e\n\x06labels\x18\x03 \x03(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\"T\n\x14\x44\x65scribeSceneRequest\x12*\n\x05image\x18\x01 \x01(\x0b\x32\x1b.safecity.ml.v1.ImageSource\x12\x10\n\x08language\x18\x02 \x01(\t\"R\n\x15\x44\x65scribeSceneResponse\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x10\n\x08ocr_text\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\"T\n\x14InferFeaturesRequest\x12*\n\x05image\x18\x01 \x01(\x0b\x32\x1b.safecity.ml.v1.ImageSource\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\"C\n\x11\x46\x65\x61turePrediction\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\"L\n\x15InferFeaturesResponse\x12\x33\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32!.safecity.ml.v1.FeaturePrediction2\xa5\x02\n\tMLService\x12\\\n\rModeratePhoto\x12$.safecity.ml.v1.ModeratePhotoRequest\x1a%.safecity.ml.v1.ModeratePhotoResponse\x12\\\n\rDescribeScene\x12$.safecity.ml.v1.DescribeSceneRequest\x1a%.safecity.ml.v1.DescribeSceneResponse\x12\\\n\rInferFeatures\x12$.safecity.ml.v1.InferFeaturesRequest\x1a%.safecity.ml.v1.InferFeaturesResponseB,Z*github.com/safecity/api/internal/mlpb;mlpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/safecity/api/internal/mlpb;mlpb'
  _globals['_IMAGESOURCE']._serialized_start=28
  _globals['_IMAGESOURCE']._serialized_end=111
  _globals['_MODERATEPHOTOREQUEST']._serialized_start=113
  _globals['_MODERATEPHOTOREQUEST']._serialized_end=179
  _globals['_MODERATEPHOTORESPONSE']._serialized_start=181
  _globals['_MODERATEPHOTORESPONSE']._serialized_end=274
  _globals['_DESCRIBESCENEREQUEST']._serialized_start=276
  _globals['_DESCRIBESCENEREQUEST']._serialized_end=360
  _globals['_DESCRIBESCENERESPONSE']._serialized_start=362
  _globals['_DESCRIBESCENERESPONSE']._serialized_end=444
  _globals['_INFERFEATURESREQUEST']._serialized_start=446
  _globals['_INFERFEATURESREQUEST']._serialized_end=530
  _globals['_FEATUREPREDICTION']._serialized_start=532
  _globals['_FEATUREPREDICTION']._serialized_end=599
  _globals['_INFERFEATURESRESPONSE']._serialized_start=601
  _globals['_INFERFEATURESRESPONSE']._serialized_end=677
  _globals['_MLSERVICE']._serialized_start=680
  _globals['_MLSERVICE']._serialized_end=973
# @@protoc_insertion_point(module_scope)
