# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ml_pb2 as ml__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ModeratePhoto = channel.unary_unary(
                '/safecity.ml.v1.MLService/ModeratePhoto',
                request_serializer=ml__pb2.ModeratePhotoRequest.SerializeToString,
                response_deserializer=ml__pb2.ModeratePhotoResponse.FromString,
                _registered_method=True)
        self.DescribeScene = channel.unary_unary(
                '/safecity.ml.v1.MLService/DescribeScene',
                request_serializer=ml__pb2.DescribeSceneRequest.SerializeToString,
                response_deserializer=ml__pb2.DescribeSceneResponse.FromString,
                _registered_method=True)
        self.InferFeatures = channel.unary_unary(
                '/safecity.ml.v1.MLService/InferFeatures',
                request_serializer=ml__pb2.InferFeaturesRequest.SerializeToString,
                response_deserializer=ml__pb2.InferFeaturesResponse.FromString,
                _registered_method=True)


class MLServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ModeratePhoto(self, request, context):
        """ModeratePhoto decides whether an uploaded photo is safe to publish.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeScene(self, request, context):
        """DescribeScene returns OCR text + a scene description (accessibility fallback).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferFeatures(self, request, context):
        """InferFeatures predicts accessibility feature values from a point photo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ModeratePhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.ModeratePhoto,
                    request_deserializer=ml__pb2.ModeratePhotoRequest.FromString,
                    response_serializer=ml__pb2.ModeratePhotoResponse.SerializeToString,
            ),
            'DescribeScene': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeScene,
                    request_deserializer=ml__pb2.DescribeSceneRequest.FromString,
                    response_serializer=ml__pb2.DescribeSceneResponse.SerializeToString,
            ),
            'InferFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.InferFeatures,
                    request_deserializer=ml__pb2.InferFeaturesRequest.FromString,
                    response_serializer=ml__pb2.InferFeaturesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'safecity.ml.v1.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('safecity.ml.v1.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ModeratePhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/safecity.ml.v1.MLService/ModeratePhoto',
            ml__pb2.ModeratePhotoRequest.SerializeToString,
            ml__pb2.ModeratePhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/safecity.ml.v1.MLService/DescribeScene',
            ml__pb2.DescribeSceneRequest.SerializeToString,
            ml__pb2.DescribeSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/safecity.ml.v1.MLService/InferFeatures',
            ml__pb2.InferFeaturesRequest.SerializeToString,
            ml__pb2.InferFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
